import random
entities = {
    'Disease': [
        'breast cancer', 'type 2 diabetes', 'chronic kidney disease',
        'acute lymphoblastic leukemia', "Alzheimer's disease", "Parkinson's disease",
        'rheumatoid arthritis', 'coronary artery disease', 'hypertensive heart disease',
        'chronic obstructive pulmonary disease', 'osteoporosis', 'multiple sclerosis',
        'inflammatory bowel disease', 'systemic lupus erythematosus',
        'acute myocardial infarction', 'chronic liver disease', 'cystic fibrosis',
        'amyotrophic lateral sclerosis', "Huntington's disease", "Crohn's disease",
        'ulcerative colitis', 'pneumocystis pneumonia', 'Ebola virus disease',
        'Zika virus infection', 'dengue fever', 'Marburg hemorrhagic fever',
        'severe acute respiratory syndrome', 'middle east respiratory syndrome',
        'COVID-19', 'avian influenza', 'swine flu', 'tuberculosis',
        'human immunodeficiency virus infection', 'acquired immunodeficiency syndrome',
        'viral hepatitis', 'herpes simplex virus infection', 'varicella-zoster virus infection',
        'measles', 'mumps', 'rubella', 'pertussis', 'diphtheria', 'tetanus',
        'polio', 'malaria', 'schistosomiasis', 'leishmaniasis', 'chagas disease',
        'sleeping sickness', 'lyme disease', 'syphilis', 'gonorrhea', 'chlamydia',
        'trichomoniasis', 'human papillomavirus infection', 'psoriasis',
        'eczema', 'atopic dermatitis', 'celiac disease', 'lactose intolerance',
        'sickle cell anemia', 'thalassemia', 'hemophilia', 'von Willebrand disease',
        'anemia of chronic disease', 'iron-deficiency anemia', 'leukemia',
        'lymphoma', 'myeloma', 'melanoma', 'basal cell carcinoma',
        'squamous cell carcinoma', 'glioblastoma multiforme', 'neuroblastoma',
        'retinoblastoma', 'Wilms tumor', 'Ewing sarcoma', 'osteosarcoma',
        'rhabdomyosarcoma', "Kaposi's sarcoma", 'adenocarcinoma', 'hepatocellular carcinoma',
        'cholangiocarcinoma', 'pancreatic cancer', 'colorectal cancer',
        'gastric cancer', 'esophageal cancer', 'lung cancer', 'prostate cancer',
        'ovarian cancer', 'cervical cancer', 'endometrial cancer', 'testicular cancer',
        'bladder cancer', 'kidney cancer', 'thyroid cancer', 'adrenal gland tumors',
        'pituitary tumors', 'parathyroid disorders', 'diabetes insipidus',
        "Addison's disease", "Cushing's syndrome", "Graves' disease",
        "Hashimoto's thyroiditis", 'myasthenia gravis', 'Guillain-Barré syndrome',
        'Lambert-Eaton myasthenic syndrome', 'dermatomyositis', 'polymyositis',
        'fibromyalgia', 'chronic fatigue syndrome', 'obstructive sleep apnea',
        'narcolepsy', 'restless legs syndrome', 'epilepsy', 'migraine',
        'tension-type headache', 'cluster headache', 'Alzheimer dementia',
        'vascular dementia', 'frontotemporal dementia', 'Lewy body dementia',
        'autism spectrum disorder', 'attention deficit hyperactivity disorder',
        'schizophrenia', 'bipolar disorder', 'major depressive disorder',
        'generalized anxiety disorder', 'panic disorder', 'obsessive-compulsive disorder',
        'post-traumatic stress disorder', 'anorexia nervosa', 'bulimia nervosa',
        'binge eating disorder', 'substance use disorder', 'alcohol dependence',
        'nicotine dependence', 'opioid use disorder', 'cannabis use disorder',
        'stimulant use disorder', 'delirium tremens', 'withdrawal syndromes',
        'hyponatremia', 'hypernatremia', 'hypokalemia', 'hyperkalemia',
        'hypocalcemia', 'hypercalcemia', 'hypomagnesemia', 'hypermagnesemia',
        'metabolic acidosis', 'metabolic alkalosis', 'respiratory acidosis',
        'respiratory alkalosis', 'dehydration', 'overhydration', 'heat stroke',
        'hypothermia', 'burns', 'frostbite', 'poisoning', 'overdose',
        'allergic rhinitis', 'asthma', 'bronchitis', 'pneumonia', 'emphysema',
        'pulmonary fibrosis', 'pulmonary embolism', 'deep vein thrombosis',
        'atherosclerosis', 'arteriosclerosis', 'hypertension', 'hypotension',
        'arrhythmias', 'atrial fibrillation', 'ventricular tachycardia',
        'ventricular fibrillation', 'heart failure', 'cardiomyopathy',
        'pericarditis', 'endocarditis', 'myocarditis', 'valvular heart disease',
        'aneurysm', 'stroke', 'transient ischemic attack', 'subarachnoid hemorrhage',
        'intracerebral hemorrhage', 'spinal cord injury', 'traumatic brain injury',
        'concussion', 'cerebral palsy', 'spina bifida', 'muscular dystrophy',
        'multiple endocrine neoplasia', 'pheochromocytoma', 'nephrotic syndrome',
        'nephritic syndrome', 'glomerulonephritis', 'pyelonephritis',
        'urinary tract infection', 'benign prostatic hyperplasia', 'erectile dysfunction',
        'infertility', 'polycystic ovary syndrome', 'endometriosis', 'menopause',
        'preeclampsia', 'eclampsia', 'gestational diabetes', 'abruptio placentae',
        'placenta previa', 'ectopic pregnancy', 'miscarriage', 'preterm labor',
        'Down syndrome', 'Turner syndrome', 'Klinefelter syndrome', 'fragile X syndrome',
        'Duchenne muscular dystrophy', 'phenylketonuria', 'galactosemia',
        "Wilson's disease", 'hemochromatosis', 'porphyria', 'alpha-1 antitrypsin deficiency',
        'hereditary spherocytosis', 'G6PD deficiency', 'Marfan syndrome',
        'Ehlers-Danlos syndrome', 'osteogenesis imperfecta', 'achondroplasia',
        'familial hypercholesterolemia', "Leber's hereditary optic neuropathy",
        'retinitis pigmentosa', 'macular degeneration', 'glaucoma', 'cataract',
        'diabetic retinopathy', 'hypertensive retinopathy', 'optic neuritis',
        'uveitis', 'conjunctivitis', 'keratitis', 'blepharitis', 'sty',
        'otitis media', 'otitis externa', "Meniere's disease", 'tinnitus',
        'hearing loss', 'vertigo', 'sinusitis', 'pharyngitis', 'laryngitis',
        'tonsillitis', 'epiglottitis', 'bronchiolitis', 'croup', 'whooping cough',
        'smallpox', 'anthrax', 'plague', 'typhoid fever', 'cholera', 'leprosy',
        'gas gangrene', 'necrotizing fasciitis', 'MRSA infection', 'C. difficile infection',
        'E. coli infection', 'Salmonella infection', 'Shigella infection',
        'Listeria infection', 'Campylobacter infection', 'Helicobacter pylori infection',
        'Norovirus infection', 'Rotavirus infection', 'Hepatitis A', 'Hepatitis B',
        'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Yellow fever', 'West Nile virus infection',
        'Japanese encephalitis', 'Rabies', 'Hantavirus pulmonary syndrome',
        'Lassa fever', 'Rift Valley fever', 'Crimean-Congo hemorrhagic fever',
        'Chikungunya fever', 'influenza', 'common cold', 'respiratory syncytial virus infection',
    ],
    'Chemical': [
        'acetylsalicylic acid', 'hydrochlorothiazide', 'metformin hydrochloride',
        'cisplatin', 'doxorubicin hydrochloride', 'n-acetylcysteine', 'folic acid',
        'omega-3 fatty acids', 'paracetamol', 'ibuprofen', 'naproxen', 'diclofenac',
        'celecoxib', 'omeprazole', 'lansoprazole', 'pantoprazole', 'ranitidine',
        'cimetidine', 'famotidine', 'loratadine', 'cetirizine', 'fexofenadine',
        'diphenhydramine', 'pseudoephedrine', 'phenylephrine', 'oxymetazoline',
        'albuterol', 'salmeterol', 'formoterol', 'tiotropium', 'ipratropium',
        'fluticasone', 'budesonide', 'prednisone', 'methylprednisolone',
        'hydrocortisone', 'dexamethasone', 'betamethasone', 'insulin glargine',
        'insulin lispro', 'metformin', 'glipizide', 'glyburide', 'pioglitazone',
        'rosiglitazone', 'sitagliptin', 'linagliptin', 'canagliflozin',
        'dapagliflozin', 'empagliflozin', 'levothyroxine', 'liothyronine',
        'methimazole', 'propylthiouracil', 'propranolol', 'atenolol', 'metoprolol',
        'carvedilol', 'labetalol', 'amlodipine', 'nifedipine', 'diltiazem',
        'verapamil', 'hydralazine', 'nitroglycerin', 'isosorbide mononitrate',
        'digoxin', 'warfarin', 'heparin', 'enoxaparin', 'apixaban', 'rivaroxaban',
        'dabigatran', 'clopidogrel', 'ticagrelor', 'prasugrel', 'aspirin',
        'atorvastatin', 'simvastatin', 'pravastatin', 'rosuvastatin',
        'lovastatin', 'ezetimibe', 'furosemide', 'bumetanide', 'torsemide',
        'spironolactone', 'eplerenone', 'chlorthalidone', 'amiloride', 'triamterene',
        'lisinopril', 'enalapril', 'ramipril', 'captopril', 'losartan',
        'valsartan', 'irbesartan', 'candesartan', 'telmisartan', 'olmesartan',
        'penicillin', 'amoxicillin', 'ampicillin', 'cephalexin', 'ceftriaxone',
        'cefepime', 'vancomycin', 'daptomycin', 'linezolid', 'azithromycin',
        'clarithromycin', 'erythromycin', 'clindamycin', 'gentamicin',
        'tobramycin', 'amikacin', 'doxycycline', 'minocycline', 'levofloxacin',
        'ciprofloxacin', 'moxifloxacin', 'trimethoprim-sulfamethoxazole',
        'metronidazole', 'rifampin', 'isoniazid', 'pyrazinamide', 'ethambutol',
        'acyclovir', 'valacyclovir', 'ganciclovir', 'oseltamivir', 'zanamivir',
        'sofosbuvir', 'ledipasvir', 'velpatasvir', 'remdesivir', 'chloroquine',
        'hydroxychloroquine', 'artemether', 'lumefantrine', 'mefloquine',
        'quinine', 'pyrimethamine', 'sulfadoxine', 'praziquantel', 'albendazole',
        'mebendazole', 'ivermectin', 'flucytosine', 'fluconazole', 'itraconazole',
        'voriconazole', 'amphotericin B', 'nystatin', 'terbinafine', 'griseofulvin',
        'ketamine', 'propofol', 'etomidate', 'midazolam', 'fentanyl', 'morphine',
        'hydromorphone', 'oxycodone', 'codeine', 'tramadol', 'naloxone',
        'buprenorphine', 'methadone', 'diazepam', 'lorazepam', 'alprazolam',
        'clonazepam', 'zolpidem', 'eszopiclone', 'ramelteon', 'haloperidol',
        'risperidone', 'olanzapine', 'quetiapine', 'aripiprazole', 'clozapine',
        'sertraline', 'fluoxetine', 'paroxetine', 'citalopram', 'escitalopram',
        'venlafaxine', 'duloxetine', 'bupropion', 'mirtazapine', 'lithium carbonate',
        'valproic acid', 'carbamazepine', 'lamotrigine', 'gabapentin',
        'pregabalin', 'levetiracetam', 'topiramate', 'phenytoin', 'phenobarbital',
        'methotrexate', 'cyclophosphamide', 'vincristine', 'vinblastine',
        'paclitaxel', 'docetaxel', 'imatinib', 'rituximab', 'trastuzumab',
        'bevacizumab', 'nivolumab', 'pembrolizumab', 'ipilimumab', 'atezolizumab',
        'aldesleukin', 'interferon alpha', 'interferon beta', 'epoetin alfa',
        'filgrastim', 'sargramostim', 'theophylline', 'montelukast', 'zafirlukast',
        'omalizumab', 'leuprolide', 'goserelin', 'bicalutamide', 'flutamide',
        'tamoxifen', 'raloxifene', 'anastrozole', 'letrozole', 'exemestane',
        'medroxyprogesterone', 'levonorgestrel', 'etonogestrel', 'drospirenone',
        'norethindrone', 'ethinyl estradiol', 'estradiol valerate', 'conjugated estrogens'
    ],
    'Protein': [
        'tumor necrosis factor', 'vascular endothelial growth factor',
        'insulin-like growth factor', 'amyloid beta peptide', 'C-reactive protein',
        'interleukin 6', 'erythropoietin receptor', 'nuclear factor kappa B',
        'p53 tumor suppressor protein', 'BRCA1 protein', 'BRCA2 protein',
        'cyclooxygenase-2', 'matrix metalloproteinase-9', 'alpha-synuclein',
        'tau protein', 'myelin basic protein', 'dopamine transporter',
        'serotonin transporter', 'glutamate receptor', 'gamma-aminobutyric acid receptor',
        'epidermal growth factor receptor', 'fibroblast growth factor',
        'transforming growth factor beta', 'platelet-derived growth factor',
        'interferon gamma', 'interleukin 1 beta', 'interleukin 2', 'interleukin 4',
        'interleukin 10', 'interleukin 17', 'interleukin 23', 'hemoglobin A1c',
        'low-density lipoprotein receptor', 'apolipoprotein E', 'albumin',
        'fibrinogen', 'thrombin', 'plasminogen', 'angiotensin-converting enzyme',
        'renin', 'aldosterone', 'natriuretic peptide', 'corticotropin-releasing hormone',
        'adrenocorticotropic hormone', 'growth hormone', 'prolactin', 'oxytocin',
        'vasopressin', 'thyroid-stimulating hormone', 'triiodothyronine',
        'thyroxine', 'parathyroid hormone', 'calcitonin', 'insulin', 'glucagon',
        'somatostatin', 'pancreatic polypeptide', 'ghrelin', 'leptin',
        'adiponectin', 'resistin', 'secretin', 'cholecystokinin', 'gastrin',
        'pepsinogen', 'trypsin', 'chymotrypsin', 'lipase', 'amylase',
        'lactase', 'sucrase', 'maltase', 'hepcidin', 'ceruloplasmin',
        'transferrin', 'ferritin', 'myoglobin', 'troponin I', 'troponin T',
        'creatine kinase', 'lactate dehydrogenase', 'alkaline phosphatase',
        'alanine transaminase', 'aspartate transaminase', 'gamma-glutamyl transferase',
        'bilirubin', 'urea', 'creatinine', 'cystatin C', 'glutathione',
        'superoxide dismutase', 'catalase', 'peroxiredoxin', 'thioredoxin',
        'heat shock protein 70', 'ubiquitin', 'proteasome', 'telomerase',
        'reverse transcriptase', 'integrase', 'RNA polymerase', 'DNA polymerase',
        'topoisomerase', 'helicase', 'ligase', 'endonuclease', 'exonuclease',
        'histone', 'tubulin', 'actin', 'myosin', 'keratin', 'collagen',
        'elastin', 'fibrillin', 'fibronectin', 'laminin', 'cadherin',
        'integrin', 'selectin', 'connexin', 'clathrin', 'adaptin', 'dynamin',
        'synaptotagmin', 'syntaxin', 'SNARE proteins', 'G protein',
        'adenylyl cyclase', 'phospholipase C', 'protein kinase A',
        'protein kinase C', 'calmodulin', 'phosphodiesterase', 'ras protein',
        'raf kinase', 'mitogen-activated protein kinase', 'JAK kinase',
        'STAT proteins', 'PI3 kinase', 'Akt kinase', 'mTOR',
        'cyclin-dependent kinase', 'cyclins', 'retinoblastoma protein',
        'E2F transcription factor', 'c-Jun N-terminal kinase', 'p38 MAP kinase',
        'NFAT transcription factor', 'nuclear hormone receptor', 'androgen receptor',
        'estrogen receptor', 'progesterone receptor', 'glucocorticoid receptor',
        'mineralocorticoid receptor', 'peroxisome proliferator-activated receptor',
        'retinoic acid receptor', 'vitamin D receptor', 'aryl hydrocarbon receptor',
        'Toll-like receptor', 'NOD-like receptor', 'RIG-I-like receptor',
        'interferon regulatory factor', 'major histocompatibility complex',
        'immunoglobulin G', 'immunoglobulin M', 'immunoglobulin A',
        'immunoglobulin E', 'immunoglobulin D', 'T cell receptor', 'CD4',
        'CD8', 'CD19', 'CD20', 'CD28', 'B cell receptor', 'complement proteins',
        'C1q', 'C3 convertase', 'C5a', 'defensins', 'lysozyme', 'lactoferrin',
        'beta-2 microglobulin', 'alpha-fetoprotein', 'prostate-specific antigen',
        'cancer antigen 125', 'carcinoembryonic antigen', 'HER2/neu receptor',
        'epstein-barr nuclear antigen', 'reverse transcriptase', 'hemagglutinin',
        'neuraminidase', 'spike protein', 'nucleocapsid protein', 'membrane protein',
        'envelope protein', 'RNA-dependent RNA polymerase', 'nonstructural proteins'
    ]
}

entity_sentences = [
    "The patient was diagnosed with {ENTITY}.",
    "{ENTITY} is a common condition affecting millions worldwide.",
    "Treatment with {ENTITY} has shown positive results.",
    "The study focused on the effects of {ENTITY}.",
    "Symptoms of {ENTITY} include cough and fever.",
    "Researchers discovered a link between {ENTITY} and immune response.",
    "{ENTITY} therapy may reduce disease progression.",
    "The mechanism of {ENTITY} action involves multiple pathways.",
    "Early detection of {ENTITY} improves prognosis.",
    "Patients with {ENTITY} often require specialized care.",
    "The effectiveness of {ENTITY} was evaluated in clinical trials.",
    "{ENTITY} levels were measured in the blood samples.",
    "Side effects of {ENTITY} can include nausea and dizziness.",
    "The prevalence of {ENTITY} increases with age.",
    "Vaccination against {ENTITY} is highly recommended.",
    "Genetic mutations in {ENTITY} genes can lead to disease.",
    "{ENTITY} inhibitors are used in targeted therapies.",
    "Lifestyle changes can help manage {ENTITY} symptoms.",
    "The role of {ENTITY} in cell signaling is significant.",
    "{ENTITY} was administered intravenously.",
    "The presence of {ENTITY} antibodies indicates exposure.",
    "Environmental factors contribute to {ENTITY} development.",
    "{ENTITY} expression was upregulated in the samples.",
    "Combination therapy with {ENTITY} improved outcomes.",
    "The patient tested positive for {ENTITY}.",
    "Research on {ENTITY} is ongoing.",
    "{ENTITY} can be transmitted through contact.",
    "The structure of {ENTITY} was analyzed using imaging techniques.",
    "{ENTITY} deficiency can cause metabolic disorders.",
    "Monitoring {ENTITY} levels is crucial during treatment.",
    "The interaction between {ENTITY} and receptors was studied.",
    "Resistance to {ENTITY} poses a challenge in treatment.",
    "{ENTITY} screening is part of routine check-ups.",
    "The function of {ENTITY} in the body is vital.",
    "{ENTITY} was isolated from the sample.",
    "The effects of {ENTITY} overdose are severe.",
    "Patients were grouped based on {ENTITY} status.",
    "The discovery of {ENTITY} opened new research avenues.",
    "Management of {ENTITY} involves multidisciplinary teams.",
    "{ENTITY} mutations were detected using sequencing methods.",
    "Clinical guidelines for {ENTITY} have been updated.",
    "{ENTITY} therapy requires careful monitoring.",
    "The relationship between {ENTITY} and inflammation is complex.",
    "High levels of {ENTITY} indicate disease progression.",
    "The patient was treated for {ENTITY} complications.",
    "Studies suggest that {ENTITY} may have protective effects.",
    "The spread of {ENTITY} can be prevented with proper hygiene.",
    "{ENTITY} plays a crucial role in metabolic pathways.",
    "Side effects of {ENTITY} are generally mild.",
    "The test measures the concentration of {ENTITY} in the blood.",
    "Administration of {ENTITY} requires careful dosage adjustments.",
    "{ENTITY} was found to inhibit the growth of certain cells.",
    "Clinical manifestations of {ENTITY} vary among individuals.",
    "The prevalence of {ENTITY} has decreased due to effective vaccines.",
    "Studies indicate that {ENTITY} may have anti-inflammatory properties.",
    "The patient underwent surgery to remove {ENTITY}.",
    "{ENTITY} is considered a marker for disease severity.",
    "The effectiveness of {ENTITY} is influenced by genetic factors.",
    "Researchers are exploring new therapies targeting {ENTITY}.",
    "Early intervention with {ENTITY} can prevent complications.",
    "The development of {ENTITY} vaccines is a global priority.",
    "{ENTITY} levels were significantly higher in the experimental group.",
    "The patient showed an allergic reaction to {ENTITY}.",
    "Long-term use of {ENTITY} may lead to side effects.",
    "The binding affinity of {ENTITY} was measured using assays.",
    "New diagnostic methods for detecting {ENTITY} are being developed.",
    "{ENTITY} was synthesized in the laboratory.",
    "The function of {ENTITY} is essential in the immune response.",
    "Overexpression of {ENTITY} can lead to tumor growth.",
    "The pharmacokinetics of {ENTITY} were studied in animal models.",
    "The patient received a transplant to treat {ENTITY}.",
    "Inhibition of {ENTITY} activity reduces symptoms.",
    "The clinical trial assessed the safety of {ENTITY} therapy.",
    "Researchers are investigating the role of {ENTITY} in aging.",
    "The prevalence of {ENTITY} varies by geographic region.",
    "{ENTITY} is a key target in drug development.",
    "The interaction between {ENTITY} and DNA was analyzed.",
    "Patients with high {ENTITY} levels may require intensive care.",
    "{ENTITY} is involved in metabolic regulation.",
    "The gene encoding {ENTITY} was mutated in the sample.",
    "Treatment protocols involving {ENTITY} are being standardized.",
    "The study evaluated the efficacy of {ENTITY}-based treatments.",
    "Exposure to {ENTITY} can cause adverse health effects.",
    "Diagnostic imaging revealed accumulation of {ENTITY} in tissues.",
    "The patient was enrolled in a study focusing on {ENTITY}.",
    "The therapeutic window for {ENTITY} administration is narrow.",
    "Elevated {ENTITY} concentrations indicate an inflammatory response.",
    "The molecular structure of {ENTITY} was determined via crystallography.",
    "{ENTITY}-induced toxicity was observed in the experiment.",
    "Preventative measures against {ENTITY} are essential in healthcare.",
    "The metabolism of {ENTITY} varies among individuals.",
    "Clinical signs of {ENTITY} include weakness and fatigue.",
    "The patient received combination therapy including {ENTITY}.",
    "Genetic testing can identify susceptibility to {ENTITY}.",
    "Researchers are developing {ENTITY} analogs with improved properties.",
    "The role of {ENTITY} in signal transduction was examined.",
    "Administration of {ENTITY} led to remission in some cases.",
    "The patient exhibited resistance to {ENTITY} treatment.",
    "Biomarkers for {ENTITY} were identified in the study.",
    "Vaccination strategies for {ENTITY} are being optimized.",
    "The patient reported adverse effects after taking {ENTITY}.",
    "Levels of {ENTITY} decrease with effective therapy.",
    "The genetic sequence of {ENTITY} was analyzed.",
    "Exposure to {ENTITY} is linked to occupational hazards.",
    "The study assessed patient outcomes after {ENTITY} therapy.",
    "A novel form of {ENTITY} has been discovered.",
    "The regulation of {ENTITY} expression is complex.",
    "Treatment delays in {ENTITY} cases can worsen prognosis.",
    "The patient's response to {ENTITY} was monitored closely.",
    "Environmental contamination with {ENTITY} poses health risks.",
    "Therapeutic approaches targeting {ENTITY} are under investigation.",
    "The effectiveness of {ENTITY} depends on dosage and duration.",
    "{ENTITY} plays a pivotal role in cell apoptosis.",
    "Early symptoms of {ENTITY} are often nonspecific.",
    "Clinical management of {ENTITY} requires multidisciplinary collaboration.",
    "The research focuses on the inhibition of {ENTITY} activity.",
    "Serum levels of {ENTITY} serve as diagnostic indicators.",
    "Advancements in {ENTITY} research have led to new treatments.",
    "The patient was screened for {ENTITY} antibodies.",
    "Strategies to enhance {ENTITY} stability are being explored.",
    "{ENTITY} accumulation was observed in the liver.",
    "The patient underwent therapy targeting {ENTITY} overexpression.",
    "Dietary intake of {ENTITY} was assessed in the study.",
    "The use of {ENTITY} is contraindicated in certain conditions.",
    "Gene therapy approaches aim to correct {ENTITY} deficiencies.",
    "The clinical trial tests a vaccine against {ENTITY}.",
    "Patients were advised to avoid exposure to {ENTITY}.",
    "The pathogenesis of {ENTITY} involves multiple factors.",
    "Pharmacological inhibition of {ENTITY} shows promise.",
    "New biomarkers for detecting {ENTITY} are under development.",
    "The patient received supportive care for {ENTITY} symptoms.",
    "The prevalence of {ENTITY} is higher in urban areas.",
    "Molecular mechanisms of {ENTITY} action were elucidated.",
    "The half-life of {ENTITY} in plasma was determined.",
    "Genetic polymorphisms affect {ENTITY} metabolism.",
    "Standard treatment regimens for {ENTITY} are evolving.",
    "Patient education about {ENTITY} management is important.",
    "The study investigates resistance mechanisms to {ENTITY}.",
    "Levels of {ENTITY} were normalized after treatment.",
    "The relationship between {ENTITY} and oxidative stress was studied.",
    "Clinical trials are testing the efficacy of {ENTITY} derivatives.",
    "The patient experienced remission following {ENTITY} therapy.",
    "The role of {ENTITY} in neural development is significant.",
    "Research suggests that {ENTITY} may have neuroprotective effects.",
    "The expression of {ENTITY} is regulated by transcription factors.",
    "The patient's {ENTITY} levels remained stable during the study.",
    "Advances in technology aid in detecting {ENTITY} mutations.",
    "The pharmacodynamics of {ENTITY} were characterized.",
    "Combination of {ENTITY} with other agents enhances efficacy.",
    "Longitudinal studies track the progression of {ENTITY} over time.",
    "The patient was enrolled in a clinical trial for {ENTITY}.",
    "Reduced activity of {ENTITY} has been linked to disease.",
    "Researchers are studying the impact of {ENTITY} on metabolism.",
    "The patient exhibited classic signs of {ENTITY}.",
    "Efforts to eradicate {ENTITY} have been intensified.",
    "The study examined the role of {ENTITY} in cellular aging.",
    "Current therapies targeting {ENTITY} are limited.",
    "The production of {ENTITY} increases during stress.",
    "Novel compounds inhibit {ENTITY} function effectively.",
    "The presence of {ENTITY} was confirmed through testing.",
    "Patients with {ENTITY} require regular monitoring.",
    "Understanding {ENTITY} interactions is crucial for drug design.",
    "The patient was prescribed medication to manage {ENTITY}.",
    "Elevated {ENTITY} levels correlate with disease severity.",
    "The effect of diet on {ENTITY} expression was investigated.",
    "Scientists are exploring how {ENTITY} affects the brain.",
    "The study aims to develop new diagnostics for {ENTITY}.",
    "Increased awareness of {ENTITY} can improve early detection.",
    "{ENTITY} serves as a biomarker for certain conditions.",
    "The genetic basis of {ENTITY} susceptibility was studied.",
    "Patient outcomes improve with early {ENTITY} intervention.",
    "The molecular pathways involving {ENTITY} are complex.",
    "Public health initiatives focus on reducing {ENTITY} incidence.",
    "The research explores the evolutionary history of {ENTITY}.",
    "Therapeutic antibodies targeting {ENTITY} are under development.",
    "Long-term exposure to {ENTITY} can be harmful.",
    "The regulation of {ENTITY} involves multiple genes.",
    "Clinical features of {ENTITY} vary widely.",
    "The patient was advised about potential {ENTITY} risks.",
    "Advances in imaging enhance detection of {ENTITY}.",
    "The role of {ENTITY} in inflammation is being researched.",
    "The study investigates the genetic diversity of {ENTITY}.",
    "Effective vaccines against {ENTITY} are not yet available.",
    "The metabolism of {ENTITY} produces reactive intermediates.",
    "Researchers are mapping the distribution of {ENTITY} globally.",
    "The patient consented to participate in {ENTITY} research.",
    "Understanding {ENTITY} dynamics can inform treatment strategies.",
    "The study found no significant effect of {ENTITY} on survival.",
    "The interaction of {ENTITY} with cell membranes was analyzed.",
    "Guidelines recommend screening for {ENTITY} in high-risk groups.",
    "The efficacy of {ENTITY} varies with administration route.",
    "A reduction in {ENTITY} activity was observed post-treatment.",
    "Emerging therapies target the synthesis of {ENTITY}.",
    "The patient underwent genetic counseling for {ENTITY}.",
    "Laboratory tests detect {ENTITY} with high specificity.",
    "The expression levels of {ENTITY} were quantified.",
    "The role of {ENTITY} in disease mechanisms is under study.",
    "Clinical signs of {ENTITY} resolved after intervention.",
    "The patient reported no prior history of {ENTITY}.",
    "Researchers aim to develop inhibitors of {ENTITY}.",
    "Strategies to modulate {ENTITY} activity are being tested.",
    "The prevalence of {ENTITY} has increased over the past decade.",
    "The study assessed the impact of {ENTITY} on quality of life.",
    "Exposure to {ENTITY} during development has lasting effects.",
    "Diagnostic criteria for {ENTITY} are being refined.",
    "The patient was monitored for potential {ENTITY}-related complications.",
    "Novel therapeutic agents targeting {ENTITY} are promising.",
    "The regulation of {ENTITY} involves epigenetic mechanisms.",
    "The efficacy of {ENTITY} was demonstrated in preclinical models.",
    "Treatment adherence is crucial in managing {ENTITY}.",
    "The patient showed improvement after initiation of {ENTITY} therapy.",
    "Research funding for {ENTITY} has increased significantly.",
    "Public awareness campaigns about {ENTITY} are underway.",
    "The patient experienced side effects associated with {ENTITY}.",
    "Understanding {ENTITY} resistance mechanisms is critical.",
    "The study explores the pharmacogenomics of {ENTITY}.",
    "Advancements in {ENTITY} detection methods enhance diagnosis.",
    "Management of {ENTITY} includes both pharmacological and non-pharmacological approaches.",
    "International collaboration is key to combating {ENTITY}.",
    "The safety profile of {ENTITY} was evaluated.",
    "Clinical trials for {ENTITY} therapies are in phase III.",
    "The genetic mutation causing {ENTITY} was identified.",
    "Patients with {ENTITY} have a higher risk of complications.",
    "The potential of {ENTITY} as a therapeutic target is significant.",
    "The patient's family history revealed instances of {ENTITY}.",
    "The role of {ENTITY} in chronic diseases is being investigated.",
    "Early screening for {ENTITY} can improve treatment outcomes.",
    "The stability of {ENTITY} under different conditions was tested.",
    "The patient was advised to modify lifestyle factors affecting {ENTITY}.",
    "Bioinformatics tools were used to analyze {ENTITY} data.",
    "Long-term prognosis of {ENTITY} depends on multiple factors.",
    "Combination therapies involving {ENTITY} are more effective.",
    "Ethical considerations are important in {ENTITY} research.",
    "Patient adherence to {ENTITY} treatment was monitored.",
    "The prevalence of {ENTITY} among different populations was compared.",
    "The patient enrolled in a support program for {ENTITY} management.",
    "The study examines environmental influences on {ENTITY}.",
    "Advancements in nanotechnology aid in delivering {ENTITY}.",
    "Genomic studies reveal variations in {ENTITY} among individuals.",
    "The efficacy of {ENTITY} is reduced in resistant strains.",
    "Lifestyle interventions can complement {ENTITY} therapy.",
    "The patient's recovery from {ENTITY} was remarkable.",
    "Policy changes aim to reduce the burden of {ENTITY}."
]


# Filler sentences without entities
filler_sentences = [
    "The patient was admitted to the hospital for further evaluation.",
    "Clinical trials are essential for the development of new therapies.",
    "Symptoms include fever, fatigue, and loss of appetite.",
    "Early diagnosis can significantly improve patient outcomes.",
    "The study was conducted over a period of six months.",
    "Researchers observed a notable improvement in the control group.",
    "Side effects may vary depending on the individual.",
    "The results were consistent across multiple experiments.",
    "Treatment options should be discussed with a healthcare professional.",
    "The mechanism of action is not yet fully understood.",
    "Further research is needed to confirm these findings.",
    "The medication should be taken with food.",
    "Participants were randomly assigned to different groups.",
    "The prevalence of the condition increases with age.",
    "Data were collected from various clinical sites.",
    "Regular exercise can reduce the risk of chronic diseases.",
    "The patient reported no adverse reactions.",
    "Compliance with the treatment regimen is crucial.",
    "The findings were published in a peer-reviewed journal.",
    "Nutritional support plays a vital role in recovery.",
    "The device measures heart rate and blood pressure.",
    "Vaccination programs have reduced infection rates globally.",
    "Ethical considerations were taken into account during the study.",
    "The therapy targets specific pathways in the body.",
    "Patients should avoid alcohol while taking this medication.",
    "The survey assessed patient satisfaction levels.",
    "The disease can lead to severe complications if untreated.",
    "Genetic factors may contribute to the development of the condition.",
    "The laboratory tests returned normal results.",
    "The intervention was well-tolerated by most participants.",
    "Lifestyle modifications are recommended for better health.",
    "The new guidelines emphasize preventive care.",
    "The procedure requires minimal recovery time.",
    "The analysis revealed significant correlations.",
    "Smoking cessation reduces cardiovascular risks.",
    "The patient's history includes previous surgeries.",
    "The medication was approved by regulatory authorities.",
    "Psychological support can benefit patients with chronic illness.",
    "The research team presented their findings at the conference.",
    "The sample size was sufficient for statistical analysis.",
    "The treatment duration varies depending on the severity.",
    "Informed consent was obtained from all participants.",
    "The medication interacts with certain over-the-counter drugs.",
    "Imaging techniques were used to diagnose the condition.",
    "The patient was referred to a specialist.",
    "The study aims to improve existing therapeutic strategies.",
    "Monitoring is necessary to adjust dosages appropriately.",
    "The condition is more prevalent in certain populations.",
    "Patient education is essential for disease management.",
    "The therapy has shown promise in preliminary studies.",
    "Regular follow-up appointments are important for ongoing care.",
    "Blood samples were collected for biochemical analysis.",
    "The participants completed a questionnaire about their symptoms.",
    "The medication should be stored at room temperature.",
    "Exercise intensity should be adjusted based on individual capacity.",
    "Baseline measurements were taken before the intervention.",
    "The patient's vital signs were within normal limits.",
    "A multidisciplinary approach was adopted for patient care.",
    "The findings highlight the need for early intervention.",
    "Compliance rates were higher in the intervention group.",
    "Dietary supplements may not be necessary for healthy individuals.",
    "The procedure was performed under local anesthesia.",
    "The research received funding from multiple sources.",
    "Patients reported improved quality of life after treatment.",
    "All protocols were approved by the institutional review board.",
    "The study had several limitations that should be addressed.",
    "Participants were instructed to fast overnight.",
    "The data were analyzed using statistical software.",
    "Healthcare costs are a significant concern for many patients.",
    "The questionnaire assessed mental health status.",
    "Smoking is a major risk factor for many diseases.",
    "The patient presented with symptoms of fatigue and dizziness.",
    "Treatment adherence is critical for achieving desired outcomes.",
    "The healthcare team included doctors, nurses, and therapists.",
    "Adverse events were monitored throughout the study.",
    "The medication dosage was adjusted based on response.",
    "Participants were excluded if they had prior medical conditions.",
    "The patient was advised to rest and increase fluid intake.",
    "The surgery was scheduled for the following week.",
    "Family history can influence the risk of certain conditions.",
    "The study utilized a double-blind design.",
    "Nutritional counseling was provided to all participants.",
    "The laboratory uses standardized methods for testing.",
    "Participants provided written informed consent.",
    "The patient is recovering well after the procedure.",
    "Long-term follow-up is necessary to assess outcomes.",
    "The results support the hypothesis proposed by the researchers.",
    "Regular screenings can help detect issues early.",
    "The patient was discharged with detailed care instructions.",
    "Exercise programs should be tailored to individual needs.",
    "The medication may cause drowsiness in some individuals.",
    "The study group consisted of adults aged 18 to 65 years.",
    "All data were kept confidential and secure.",
    "The therapy was administered in a clinical setting.",
    "Symptoms improved after initiating the new treatment.",
    "The patient was instructed to avoid strenuous activity.",
    "Further studies are needed to explore this relationship.",
    "Participants attended weekly sessions over three months.",
    "Regular handwashing is an effective way to prevent infection.",
    "The patient expressed concerns about potential side effects.",
    "Baseline characteristics were similar across all groups.",
    "The intervention focused on behavioral changes.",
    "Participants were recruited through local clinics.",
    "The patient was placed on a heart monitor for observation.",
    "Data integrity was maintained throughout the study.",
    "A control group was used for comparison purposes.",
    "The study was limited by its small sample size.",
    "Participants reported their daily activity levels.",
    "The healthcare provider discussed treatment options.",
    "Patient satisfaction was measured using a standardized scale.",
    "The medication should not be taken with grapefruit juice.",
    "Participants were instructed on proper inhaler technique.",
    "Sleep quality can affect overall health and well-being.",
    "The study aimed to evaluate the effectiveness of the program.",
    "No significant differences were found between the groups.",
    "The patient was encouraged to maintain a healthy diet.",
    "All procedures were conducted in accordance with guidelines.",
    "The research contributes valuable insights to the field.",
    "Patients should report any unusual symptoms to their doctor.",
    "The trial was registered in a public database.",
    "Medical records were reviewed to gather patient information.",
    "The patient was educated about the importance of medication adherence.",
    "The study examined the impact of stress on health.",
    "Participants received compensation for their time.",
    "The equipment was calibrated before each use.",
    "The patient experienced mild discomfort during the procedure.",
    "Healthcare professionals play a key role in patient education.",
    "The survey collected demographic data from respondents.",
    "Patients were instructed to return for a follow-up visit.",
    "The findings may not be generalizable to all populations.",
    "Data analysis included both quantitative and qualitative methods.",
    "The patient underwent a series of diagnostic tests.",
    "Results indicated a need for further investigation.",
    "Participants were divided into subgroups based on age.",
    "The treatment plan was adjusted based on patient feedback.",
    "The study adhered to strict ethical standards.",
    "Participants reported high levels of satisfaction with care.",
    "The patient was monitored for any signs of infection.",
    "The questionnaire was validated in previous research.",
    "Healthcare access remains a challenge in rural areas.",
    "The intervention aimed to improve physical activity levels.",
    "Data were collected at multiple time points.",
    "The patient was advised to limit caffeine intake.",
    "All staff received training on study protocols.",
    "Results were presented at an international conference.",
    "Patient autonomy is respected in all healthcare decisions.",
    "The study explored the relationship between diet and health.",
    "No adverse events were reported during the trial.",
    "The research methodology was thoroughly reviewed.",
    "The patient is scheduled for a routine check-up next month.",
    "Genetic counseling was offered to the patient's family.",
    "The participants attended educational workshops.",
    "Healthcare policies can impact patient access to services.",
    "The data set included variables such as age and gender.",
    "The patient was placed on a restricted diet.",
    "Staff members followed strict hygiene protocols.",
    "The questionnaire was administered online.",
    "Participants showed improvement over the baseline measurements.",
    "The study received ethical clearance before commencement.",
    "Patient confidentiality was maintained at all times.",
    "The clinical trial phases are carefully monitored.",
    "Medication errors can lead to serious consequences.",
    "The patient's symptoms were managed with non-pharmacological methods.",
    "The treatment protocol was standardized across all sites.",
    "Healthcare providers must stay updated on best practices.",
    "Participants were thanked for their contribution to the study.",
    "The patient was scheduled for physical therapy sessions.",
    "Medical imaging provided detailed insights into the condition.",
    "The study emphasizes the importance of early screening.",
    "The patient was cooperative and followed instructions well.",
    "Quality assurance procedures were implemented throughout the research.",
    "The therapy focuses on improving functional abilities.",
    "Participants were encouraged to express any concerns.",
    "The patient is making steady progress in rehabilitation.",
    "Healthcare resources are allocated based on community needs.",
    "The intervention led to measurable improvements in health outcomes.",
    "Regular updates were provided to all stakeholders.",
    "The patient appreciated the support from the care team.",
    "Preventive measures can reduce the incidence of illness.",
    "The study's findings have implications for future research.",
    "Patient engagement is crucial for successful treatment.",
    "The team conducted a comprehensive literature review.",
    "The patient underwent routine blood tests during the visit.",
    "Participants maintained diaries of their daily activities.",
    "The research explored innovative approaches to care.",
    "Feedback from participants was positive overall.",
    "The patient was instructed on how to use the medical device.",
    "Healthcare interventions should be evidence-based.",
    "The study was conducted in a real-world clinical setting.",
    "Participants adhered to the study protocol without issues.",
    "The importance of hydration was emphasized to the patient.",
    "Data visualization tools were used to present the results.",
    "The patient received counseling about lifestyle choices.",
    "Risk factors were identified through patient interviews.",
    "The study design minimized potential biases.",
    "Participants underwent regular assessments to track progress.",
    "The patient was satisfied with the level of care provided.",
    "The research highlights gaps in current knowledge.",
    "Training sessions were held for all research personnel.",
    "Healthcare delivery models are evolving with technology.",
    "The patient was advised to monitor symptoms at home.",
    "Ethical dilemmas were discussed during team meetings.",
    "The intervention showed promise in pilot studies.",
    "Patient-centered care improves health outcomes.",
    "The study adhered to the CONSORT guidelines.",
    "Data storage complied with privacy regulations.",
    "The patient scheduled an appointment for next week.",
    "Community health initiatives can promote wellness.",
    "The results were peer-reviewed before publication.",
    "Healthcare disparities affect underserved populations.",
    "The patient completed a satisfaction survey after discharge."
]


def generate_sentences(num_sentences, include_entities=True):
    sentences = []
    labels_list = []

    for _ in range(num_sentences):
        if include_entities and random.random() < 0.7:
            # Generate a sentence with an entity
            template = random.choice(entity_sentences)
            entity_type = random.choice(list(entities.keys()))
            entity = random.choice(entities[entity_type])
            sentence = template.replace("{ENTITY}", entity)
            words = sentence.strip('.').split()
            labels = []

            entity_words = entity.split()
            entity_len = len(entity_words)
            entity_start_idx = None

            # Find the index where the entity starts
            for idx in range(len(words) - entity_len + 1):
                if words[idx:idx+entity_len] == entity_words:
                    entity_start_idx = idx
                    break

            for idx, word in enumerate(words):
                if entity_start_idx is not None and entity_start_idx <= idx < entity_start_idx + entity_len:
                    if idx == entity_start_idx:
                        labels.append('B-' + entity_type)
                    else:
                        labels.append('I-' + entity_type)
                else:
                    labels.append('O')
        else:
            # Generate a filler sentence without entities
            sentence = random.choice(filler_sentences)
            words = sentence.strip('.').split()
            labels = ['O'] * len(words)

        # Append period at the end
        words.append('.')
        labels.append('O')

        sentences.append(words)
        labels_list.append(labels)

    return sentences, labels_list

# Generate dataset
num_sentences = 30000  # Adjust the total number of sentences as needed
sentences, labels_list = generate_sentences(num_sentences)

# Split the data into train (60%), test (20%), and validation (20%)
data = list(zip(sentences, labels_list))
random.shuffle(data)

train_split = int(0.6 * len(data))
test_split = int(0.8 * len(data))

train_data = data[:train_split]
test_data = data[train_split:test_split]
valid_data = data[test_split:]

# Function to write data to a file in CoNLL format
def write_data(filename, data):
    with open(filename, 'w', encoding='utf-8') as f:
        for words, labels in data:
            for word, label in zip(words, labels):
                f.write(f"{word}\t{label}\n")
            f.write("\n")  # Sentence separator

# Write the datasets to the specified files
write_data('Datasets/GeneratedData/train.txt', train_data)
write_data('Datasets/GeneratedData/test.txt', test_data)
write_data('Datasets/GeneratedData/valid.txt', valid_data)

print("Dataset generation and splitting complete!")
